version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: prg-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: prg
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - prg-network

volumes:
  mongo_data:

networks:
  prg-network:
    driver: bridge